"""GENERATED FILE - DO NOT EDIT.

Generated by packages/contract/src/generate.ts (`npm run gen -w @hoshen/contract`)
from packages/contract/src/{version,constants,schemas}.ts. Edit those, then
regenerate - do not hand-edit this file, it will be overwritten.

Wire-protocol constants and best-effort type hints shared with is-around (IA)
and the ha-dashboard (DV2) kiosk. TypedDicts are documentation/IDE hints only;
Home Assistant's dispatcher and this integration's own handlers do the actual
validation at runtime.
"""

from __future__ import annotations

from typing import Any, Literal, NotRequired, TypedDict

PROTOCOL_VERSION: int = 1


WS_MESSAGE_TYPES = {
    "UPDATE_STATE": "is_around/update_state",
    "PDF_CHUNK": "is_around/pdf_chunk",
    "OPERATION_RESULT": "is_around/operation_result",
}

HA_EVENTS = {
    "REQUEST_RESEND": "is_around_connector_request_resend",
    "REQUEST_OBSERVANCES": "is_around_connector_request_observances",
    "REQUEST_PDF": "is_around_connector_request_pdf",
    "REQUEST_SCHEDULE_PDF": "is_around_connector_request_schedule_pdf",
    "REQUEST_ATTENDANCE_PUSH": "is_around_connector_request_attendance_push",
    "REQUEST_ATTENDANCE_STATS": "is_around_connector_request_attendance_stats",
    "PING": "is_around_connector_ping",
    "PONG": "is_around_connector_pong",
}

HA_ENTITY_PREFIX = "sensor.is_around_connector_"

ENTITY_KEYS = {
    "WEEKLY_SCHEDULE": "weekly_schedule",
    "LESSONS": "lessons",
    "MEMORIALS": "memorials",
    "COMMUNITY_MESSAGES": "community_messages",
    "SEATING": "seating",
    "SERVICE_TYPES": "service_types",
}

LESSON_PROGRAM_KEY_PREFIX = "lesson_program_"

ENTITY_KEY_TO_ID = {
    "weekly_schedule": "sensor.is_around_connector_weekly_schedule",
    "lessons": "sensor.is_around_connector_lessons",
    "memorials": "sensor.is_around_connector_memorials",
    "community_messages": "sensor.is_around_connector_messages",
    "seating": "sensor.is_around_connector_seating",
    "service_types": "sensor.is_around_connector_service_types",
}

ENTITY_IDS = {
    "WEEKLY_SCHEDULE": "sensor.is_around_connector_weekly_schedule",
    "LESSONS": "sensor.is_around_connector_lessons",
    "MEMORIALS": "sensor.is_around_connector_memorials",
    "MESSAGES": "sensor.is_around_connector_messages",
    "SEATING": "sensor.is_around_connector_seating",
    "SERVICE_TYPES": "sensor.is_around_connector_service_types",
}

CONNECTOR_DATA_KEYS = {
    "WEEKLY_SCHEDULE_DATA": "weekly_schedule_data",
    "LESSONS_DATA": "lessons_data",
    "MEMORIALS_DATA": "memorials_data",
    "MESSAGES_DATA": "messages_data",
    "LESSON_PROGRAMS_DATA": "lesson_programs_data",
    "SEATING_DATA": "seating_data",
    "SERVICE_TYPES_DATA": "service_types_data",
}


def lesson_program_entity_key(event_date: str, order_index: int) -> str:
    """Mirrors lessonProgramEntityKey() in packages/contract/src/constants.ts."""
    date_part = event_date.replace("-", "_")
    suffix = f"_{order_index}" if order_index > 0 else ""
    return f"{LESSON_PROGRAM_KEY_PREFIX}{date_part}{suffix}"


MessageType = Literal["General", "Birth", "Grieve", "Bar", "Bat", "Army", "Wedding"]


CommunityMessageAttribute = TypedDict(
    "CommunityMessageAttribute",
    {
        "id": str | float,
        "type": MessageType,
        "body": str,
        "from": NotRequired[str],
        "to": NotRequired[str],
        "createdAt": NotRequired[str],
        "updatedAt": NotRequired[str],
    },
)


class CommunityMessagesAttributes(TypedDict):
    messages: list[CommunityMessageAttribute]
    friendly_name: NotRequired[str]
    icon: NotRequired[str]


class LessonProgramRef(TypedDict):
    id: float
    name: str
    entityId: str


class ScheduleService(TypedDict):
    name: str
    startTime: str
    _effectiveStartTime: str
    endTime: str
    duration: float | None
    locationId: str | None
    originatingServiceId: float
    serviceType: str


class DaySchedule(TypedDict):
    hebrewDate: str
    parsha: NotRequired[str]
    services: list[ScheduleService]
    is_ready: bool
    lessonPrograms: NotRequired[list[LessonProgramRef]]


class LessonAttribute(TypedDict):
    id: float
    title: str
    teacher: str | None
    dayOfWeek: float | None
    startTime: str | None
    location: str | None
    isRecurring: bool
    startDate: str | None
    endDate: str | None
    isActive: bool
    updatedAt: str


class ResolvedLessonEntry(TypedDict):
    entryType: str
    name: str
    teacher: str | None
    startTime: str
    endTime: str
    duration: float | None
    originatingEntryId: float


class LessonProgramAttributes(TypedDict):
    program_id: float
    name: str
    event_date: str
    entries: list[ResolvedLessonEntry]
    friendly_name: NotRequired[str]
    icon: NotRequired[str]


class LessonsAttributes(TypedDict):
    lessons: list[LessonAttribute]
    friendly_name: NotRequired[str]
    icon: NotRequired[str]


class MemorialAttribute(TypedDict):
    id: float
    title: str | None
    name: str
    zl: str | None
    parentsTitle: str | None
    parents: str | None
    deathTitle: str | None
    signature: str | None
    hebrewDate: str
    memorialDay: str | None
    startFreeze: NotRequired[str | None]
    endFreeze: NotRequired[str | None]
    createdAt: str
    updatedAt: str


class MemorialsAttributes(TypedDict):
    memorials: list[MemorialAttribute]
    friendly_name: NotRequired[str]
    icon: NotRequired[str]


class Observance(TypedDict):
    date: str
    name: NotRequired[str]
    type: NotRequired[str]


class ObservancesMessageData(TypedDict):
    nextObservance: NotRequired[Observance]


class ObservancesMessage(TypedDict):
    type: Literal["is_around/update_state"]
    config_entry_id: str
    data: ObservancesMessageData


class OperationResultMessage(TypedDict):
    type: Literal["is_around/operation_result"]
    config_entry_id: str
    request_id: NotRequired[str]
    success: bool
    error_message: NotRequired[str]
    message: NotRequired[str]
    data: NotRequired[dict[str, Any]]


class PdfChunkMessage(TypedDict):
    type: Literal["is_around/pdf_chunk"]
    config_entry_id: str
    request_id: str
    chunk_index: float
    total_chunks: float
    kind: Literal["attendance", "schedule"]
    data: str


SeatHolderNameFormat = Literal[
    "first_last", "first_only", "last_only", "free_text", "none"
]


class SeatHolder(TypedDict):
    id: str
    kind: Literal["user", "guest"]
    name_format: SeatHolderNameFormat
    first_name: str | None
    last_name: str | None
    guest_name: str | None
    display_name: str
    seat_count: float
    purchased_seats: float | None
    extra_seats: float


class Seat(TypedDict):
    row: float
    column: float
    seat_number: str | None
    available: bool
    holder_id: str | None


SeatingCellType = Literal[
    "seat", "aisle", "stage", "cabin", "separator", "podium", "exit", "empty"
]


class SeatingSummary(TypedDict):
    seats: float
    allocated: float
    free: float
    guest_seats: float
    users: float
    guests: float
    over_allocated_users: float
    extra_seats: float


class SeatingMap(TypedDict):
    id: float
    name: str
    description: str | None
    is_default: bool
    free_allocation: bool
    rows: float
    columns: float
    grid: list[list[SeatingCellType]]
    seats: list[Seat]
    holders: dict[str, SeatHolder]
    summary: SeatingSummary


class SeatingAttributes(TypedDict):
    maps: dict[str, SeatingMap]
    default_map: str | None
    friendly_name: NotRequired[str]
    icon: NotRequired[str]


class ServiceTypeDef(TypedDict):
    key: str
    label: str
    color: str | None
    order: float


class ServiceTypesAttributes(TypedDict):
    service_types: dict[str, ServiceTypeDef]
    friendly_name: NotRequired[str]
    icon: NotRequired[str]


class UpdateStateMessageData(TypedDict):
    entity_id: str
    state: str
    attributes: NotRequired[dict[str, Any]]


class UpdateStateMessage(TypedDict):
    type: Literal["is_around/update_state"]
    config_entry_id: str
    entity_key: NotRequired[str]
    protocol_version: NotRequired[float]
    data: UpdateStateMessageData


class WeeklyScheduleAttributes(TypedDict):
    schedules: dict[str, DaySchedule]
    friendly_name: NotRequired[str]
    icon: NotRequired[str]
